title: Varada Venkata Krishna Mangalagi
logo: /assets/img/Varada.jpg
description: Full-stack developer specialized in building chatbots, mobile, and web applications over 8 years
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
